# Site Settings
title: Hello
email: taniarascia@gmail.com
description:  My Personal website
baseurl: "/my_personal_website_and_blog"
url: "https://julesb22.github.io"
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
