# Site Settings
title: My personal website
email: julesboiteux@gmail.com
description: >
  This is my personal website
baseurl: ""
url: "http://julesboiteux.github.io"
twitter_username:
github_username:
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
