# Site Settings
title: Jules Boiteux
email: julesboiteux@gmail.com
description: My Personal website
baseurl: "/my_personal_website_and_blog"
url: "https://julesb22.github.io/"
twitter_username: jules_boiteux
github_username:  julesb22
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
